name: Modify Package Manifest
description: "Modifies a Package.swift file to reference a binary target with the given details"

inputs:
  PACKAGE_MANIFEST_PATH:
    description: "The path to the Package.swift file to be modified"
    required: true
  RELEASE_ZIP_ARTIFACT_URL:
    description: "URL of the uploaded zipped XCFramework artifact"
    required: true
  RELEASE_ZIP_CHECKSUM:
    description: "The checksum of the release's zipped artifact"
    required: true

runs:
  using: "composite"
  steps:
    - name: Update Package.swift
      shell: sh
      run: "${{ github.action_path }}/modify-package-manifest.sh -p ${{ inputs.PACKAGE_MANIFEST_PATH }} -u ${{ inputs.RELEASE_ZIP_ARTIFACT_URL }} -c ${{ inputs.RELEASE_ZIP_CHECKSUM }}"